routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('posts', 'PostController');

// Route::post('delete/{id}', 'PostController@delete');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'nama_product', 'description', 'price', 'qty',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $posts = Post::all();
        // dd($posts);

        // $posts = Post::orderBy('created_at', 'desc')->paginate(5);

        $posts = Post::paginate(5);

        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_product'=> 'required|max:255',
            'description'=> 'required|max:255',
            'price'=> 'required|max:255',
            'qty'=> 'required|max:255'
        ]);

        $post = new Post([
            'nama_product' => $request->get('nama_product'),
            'description' => $request->get('description'),
            'price' => $request->get('price'),
            'qty' => $request->get('qty')
        ]);

        $post->save();

        return redirect('/posts')->with('success', 'Data Berhasil Disimpan!.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);

        return view('posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);

        return view('posts.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama_product'=> 'required|max:255',
            'description'=> 'required|max:255',
            'price'=> 'required|max:255',
            'qty'=> 'required|max:255'
        ]);

        $post = Post::find($id);
        $post->nama_product = $request->get('nama_product');
        $post->description = $request->get('description');
        $post->price = $request->get('price');
        $post->qty = $request->get('qty');
        $post->save();

        return redirect('/posts')->with('success', 'Data Berhasil Diedit!.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
        $post->delete();

        return redirect('/posts')->with('success', 'Data Berhasil Dihapus!.');
    }


    // public function delete($id)
    // {
    //     $delete = Post::where('id', $id)->delete();

    //     // check data deleted or not
    //     if ($delete == 1){
    //         $success = true;
    //         $message = "Data Berhasil Dihapus !.";
    //     } else {
    //         $success = true;
    //         $message = "Data not found";
    //     }

    //     // Return response
    //     return response()->json([
    //         'success' => $success,
    //         'message' => $message,
    //     ]);

    //     redirect('/posts')->with('success', 'Data Berhasil Dihapus!.');

    // }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <h4>Selamat datang, <b>{{ Auth::user()->email }}</b> </h4>
                    <br/>
                    <a class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Tambah Data" href="{{ route('posts.index') }}"><i class="fa fa-plus-circle"> Add A More Products</i></a>

                    <a class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Logout" href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();">
                        <i class="fa fa-sign-out">{{ __('Logout') }}</i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!-- SweetAlert2 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.2.0/sweetalert2.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.2.0/sweetalert2.all.min.js"></script>

    <title>@yield('title')</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <div class="container">
    <a class="navbar-brand" href="{{ route('home') }}">A LARAVEL CRUD Sample</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Authentication Links -->
	@guest
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            
            @if(Auth::id())
                <li class="nav-item active">
                    <a class="nav-link " href="{{ route('home') }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('posts.index') }}">Add A Products</a>
                </li>
            @endif
            
            <li class="nav-item">
                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
            </li>
            @if (Route::has('register'))
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                </li>
            @endif
        </ul>

        @else
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ route('home') }}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('posts.index') }}">Add A Products</a>
            </li>

            <li class="nav-item dropdown active">
                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                    {{ Auth::user()->email }} <span class="caret"></span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ route('logout') }}"
                    onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                    {{ __('Logout') }}
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
                <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
        </ul>

        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
    @endguest
    </div>
    </nav>

    <div class="container">
       @yield('content')
    </div>
    
    <script src="{{ asset('js/app.js') }}"></script>
    <script>
    $(function() {
        $('.alert-success').fadeOut(3000);
    });
    </script>
</body>
</html>

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('title', 'Tambah Data')

@section('content')
<div class="row">
<div class="col-lg-6 mx-auto">
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form method="POST" action="{{ route('posts.store') }}">
    @csrf
        <div class="form-group">
            <label for="post-name">Nama Produk</label>
            <input type="text" name="nama_product" value="{{ old('nama_product') }}" class="form-control" id="nama_product" placeholder="Nama Produk">
        </div>
        <div class="form-group">
            <label for="post-description">Description</label>
            <textarea name="description" class="form-control" id="description" placeholder="Masukkan Deskripsi">{{ old('description') }}</textarea>
        </div>
        <div class="form-group">
            <label for="post-price">Price</label>
            <input type="text" name="price" value="{{ old('price') }}"class="form-control" id="price" placeholder="Price">
        </div>
        <div class="form-group">
            <label for="post-qty">Qty</label>
            <input type="text" name="qty" value="{{ old('qty') }}" class="form-control" id="qty" placeholder="Qty">
        </div>
        <button type="submit" class="btn btn-success btn-responsive">Simpan Data</button>
        <a class="btn btn-primary btn-responsive" href="{{ route('posts.index') }}"> Cancel</a>
    </form>

    <style>
        @media (max-width: 768px) {
            .btn-responsive {
                padding:2px 4px;
                font-size:80%;
                line-height: 1;
                border-radius:3px;
            }
        }

        @media (min-width: 769px) and (max-width: 992px) {
            .btn-responsive {
                padding:4px 9px;
                font-size:90%;
                line-height: 1.2;
            }
        }
  </style>
</div>
</div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Data '.$post->nama_product)

@section('content')
<div class="row">
<div class="col-lg-6 mx-auto">
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form method="POST" action="{{ route('posts.update', $post) }}">
    @csrf
    @method('PATCH')
        <div class="form-group">
            <label for="post-name">Nama Produk</label>
            <input type="text" name="nama_product" value="{{ $post->nama_product }}" class="form-control" id="nama_product" placeholder="Nama Produk">
        </div>
        <div class="form-group">
            <label for="post-description">Description</label>
            <textarea name="description" class="form-control" id="description" placeholder="Masukkan Deskripsi">{{ $post->description }}</textarea>
        </div>
        <div class="form-group">
            <label for="post-price">Price</label>
            <input type="text" name="price" value="{{ $post->price }}"class="form-control" id="price" placeholder="Price">
        </div>
        <div class="form-group">
            <label for="post-qty">Qty</label>
            <input type="text" name="qty" value="{{ $post->qty }}" class="form-control" id="qty" placeholder="Qty">
        </div>
        <button type="submit" class="btn btn-success btn-responsive">Edit Data</button>
        <a class="btn btn-primary btn-responsive" href="{{ route('posts.index') }}"> Cancel</a>
    </form>

    <style>
        @media (max-width: 768px) {
            .btn-responsive {
                padding:2px 4px;
                font-size:80%;
                line-height: 1;
                border-radius:3px;
            }
        }

        @media (min-width: 769px) and (max-width: 992px) {
            .btn-responsive {
                padding:4px 9px;
                font-size:90%;
                line-height: 1.2;
            }
        }
    </style>
</div>
</div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('title', 'Crud Data')

@section('content')

<a href="{{ route('posts.create') }}" class="btn btn-success btn-responsive" data-toggle="tooltip" data-placement="top" title="Tambah Data"><i class="fa fa-plus-circle"> Tambah Data</i></a>

@if(session()->get('success'))
    <div class="alert alert-success mt-3">
        {{ session()->get('success') }}
    </div>
@endif

<table id="table" class="table table-striped mt-3">
    <thead>
        <tr>
        <th scope="col">ID</th>
        <th scope="col">Product Name</th>
        <th scope="col">Product Description</th>
        <th scope="col">Product Price</th>
        <th scope="col">Product Qty</th>
        <th class="table-buttons">Action</th>
        </tr>
    </thead>
    <tbody>

   <?php $no = 0; ?>
    @foreach($posts as $post)

    <?php $no++ ;?>
        <tr>
        <th scope="row">{{ $no }}</th>
        <td>{{ $post->nama_product }}</td>
        <td>{{ $post->description }}</td>
        <td>Rp. {{ $post->price }}</td>
        <td>{{ $post->qty }}</td>

        <td class="table-buttons">
            <a href="{{ route('posts.edit', $post) }}" class="btn btn-primary btn-responsive" data-toggle="tooltip" data-placement="top" title="Edit">
                <i class="fa fa-edit"> Edit</i>
            </a>

            <a href="{{ route('posts.show', $post) }}" class="btn btn-success btn-responsive" data-toggle="tooltip" data-placement="top" title="Lihat">
                <i class="fa fa-eye"> Lihat</i>
            </a>

            <form action="{{ route('posts.destroy', $post) }}" method="POST">
            @csrf
            @method('DELETE')
                <button type="submit" class="btn btn-danger btn-responsive" onclick="return confirm('Hapus Data Ini ?')" data-toggle="tooltip" data-placement="top" title="Hapus">
                    <i class="fa fa-trash"> Delete</i>
                </button>
            </form>

            <!-- <button type="submit" class="btn btn-danger" onclick="deleteConfirmation({{$post->id}})" data-toggle="tooltip" data-placement="top" title="Hapus">
                <i class="fa fa-trash"> Delete</i>
            </button> -->

        </td>
        </tr>
    @endforeach
    </tbody>
 </table>

 {{ $posts->links() }}

 <style>
    @media (max-width: 768px) {
        .btn-responsive {
            padding:2px 4px;
            font-size:80%;
            line-height: 1;
            border-radius:3px;
        }
    }

    @media (min-width: 769px) and (max-width: 992px) {
        .btn-responsive {
            padding:4px 9px;
            font-size:90%;
            line-height: 1.2;
        }
    }
  </style> 

 <!-- <script type="text/javascript">
    $(document).ready( function () {
        $('#table').DataTable();
    } );

    function deleteConfirmation(id) {
        swal({
            title: "Delete?",
            text: "Please ensure and then confirm!",
            type: "warning",
            showCancelButton: !0,
            confirmButtontext: "Yes, delete it!",
            cancelButtonText: "No, cancel!",
            reverseButtons: !0
        }).then(function (e) {

            if (e.value === true) {
                var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');

                $.ajax({
                    type: 'POST',
                    url: "{{url('/delete')}}/" + id,
                    data: {_token: CSRF_TOKEN},
                    dataType: 'JSON',
                    success: function (results) {

                        if (results.success === true) {
                            swal("Done!", results.message, "success");
                        } else {
                            swal("Error", results.message, "error");
                        }
                    }
                });
            } else {
                e.dismiss;
            }
        }, function (dismiss) {
            return false;
        })
    }

</script> -->

@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('title', $post->nama_product)

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Data</div>

                <div class="card-body">
                    <h3>{{ $post->nama_product }}</h3>
                    <p>{{ $post->description }}</p>
                    <p><b>Rp. {{ $post->price }}</b></p>
                    <p>{{ $post->qty }}</p>

                    <a class="btn btn-primary btn-responsive" href="{{ route('posts.index') }}"> Kembali</a>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    @media (max-width: 768px) {
        .btn-responsive {
            padding:2px 4px;
            font-size:80%;
            line-height: 1;
            border-radius:3px;
        }
    }

    @media (min-width: 769px) and (max-width: 992px) {
        .btn-responsive {
            padding:4px 9px;
            font-size:90%;
            line-height: 1.2;
        }
    }
</style>
@endsection